services:
  chat-db:
    image: postgres:18-alpine
    container_name: chat-db
    env_file:
      - ./env/db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - chat-mesh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  chat-idp:
    image: keycloak/keycloak:26.5
    container_name: chat-idp
    command: start-dev --import-realm
    env_file:
      - ./env/idp.env
    depends_on:
      chat-db:
        condition: service_healthy
    volumes:
      - ./keycloak-config/import:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks:
      - chat-mesh
    restart: unless-stopped

  chat-server:
    image: prosodyim/prosody:0.12
    container_name: chat-server
    env_file:
      - ./env/xmpp.env
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5281:5281"
    volumes:
      - ./prosody/config/prosody.np.cfg.lua:/etc/prosody/prosody.cfg.lua
      - ./prosody/modules:/usr/lib/prosody/modules-community
      - ./prosody/certs:/etc/prosody/certs
      - ./prosody/data:/var/lib/prosody
    networks:
      - chat-mesh
    depends_on:
      chat-idp:
        condition: service_started
    restart: unless-stopped

networks:
  chat-mesh:
    driver: bridge
