services:
  # Database
  chat-db:
    image: postgres:18-alpine
    container_name: chat-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      KC_DB_USER: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      PROSODY_DB_USER: ${PROSODY_DB_USER}
      PROSODY_DB_PASSWORD: ${PROSODY_DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - chat-mesh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Identity Provider
  chat-idp:
    image: keycloak/keycloak:26.5
    container_name: chat-idp
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://chat-db:5432/${DB_NAME}?currentSchema=keycloak_schema"
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    depends_on:
      chat-db:
        condition: service_healthy
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks:
      - chat-mesh
    restart: unless-stopped

  # XMPP Server
  chat-server:
    image: prosodyim/prosody:0.12
    container_name: chat-server
    environment:
      - DOMAIN=${DOMAIN}
      - PROSODY_ADMIN_JID=${PROSODY_ADMIN_JID}
      - PROSODY_OAUTH_SECRET=${PROSODY_OAUTH_SECRET}
      - KC_REALM=${KC_REALM}
      - DB_NAME=${DB_NAME}
      - DB_USER=${PROSODY_DB_USER}
      - DB_PASSWORD=${PROSODY_DB_PASSWORD}
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5281:5281"
    volumes:
      - ./prosody/config/prosody.np.cfg.lua:/etc/prosody/prosody.cfg.lua
      - ./prosody/modules:/usr/lib/prosody/modules-community
      - ./prosody/certs:/etc/prosody/certs
      - ./prosody/data:/var/lib/prosody
    networks:
      - chat-mesh
    depends_on:
      chat-idp:
        condition: service_started
    restart: unless-stopped

networks:
  chat-mesh:
    driver: bridge
