# WIP

services:
  # Database
  chat-db:
    image: postgres:18-alpine
    container_name: chat-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql:ro
    networks:
      - chat-mesh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Identity Provider
  chat-idp:
    image: keycloak/keycloak:26.5
    container_name: chat-idp
    command: start --optimized --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://chat-db:5432/${DB_NAME}?currentSchema=keycloak_schema"
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: sso.${DOMAIN}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true" 
    depends_on:
      chat-db:
        condition: service_healthy
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks:
      - chat-mesh
    restart: unless-stopped

  # XMPP Server
  chat-server:
    image: prosodyim/prosody:0.12
    container_name: chat-server
    environment:
      - DOMAIN=${DOMAIN}
      - PROSODY_ADMIN_JID=${PROSODY_ADMIN_JID}
      - PROSODY_OAUTH_SECRET=${PROSODY_OAUTH_SECRET}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5281:5281"
    volumes:
      - ./prosody/config/prosody.prod.cfg.lua:/etc/prosody/prosody.cfg.lua
      - ./prosody/modules:/usr/lib/prosody/modules-community
      - ./prosody/data:/var/lib/prosody
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/prosody/certs/${DOMAIN}.crt:ro
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/prosody/certs/${DOMAIN}.key:ro
    networks:
      - chat-mesh
    depends_on:
      chat-idp:
        condition: service_started
    restart: unless-stopped

networks:
  chat-mesh:
    driver: bridge
